# fly.toml app configuration file generated for roulette-app-rp8ocg on 2026-08-06T14:52:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roulette-app-rp8ocg"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"
  args = {}

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DATABASE_URL = "postgresql://neondb_owner:38OwWNQkVUxCcYpFpWOE6w@ep-morning-forest-axepirle-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
